# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm install
          npm run build

      - name: Create dist.zip
        if: ${{ startsWith( matrix.node-version, '18') }}
        run: zip -r dist.zip dist

      - name: Create dist.tar.gz
        if: ${{ startsWith( matrix.node-version, '18') }}
        run: tar -zcvf dist.tar.gz dist

      - uses: "marvinpinto/action-automatic-releases@latest"
        if: ${{ startsWith( matrix.node-version, '18') }}
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "dev"
          title: "Dev Build"
          prerelease: true
          files: |
            dist.zip
            dist.tar.gz
